name: Deploy
run-name: ${{ github.actor }} is deploying

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
      
jobs:  
  deploy:
     runs-on: ubuntu-latest  
     steps:
                   
            
                 
         - name: Deploy app to droplet
           uses: appleboy/ssh-action@v0.1.4
           with:
             host: ${{ secrets.SSH_HOST }}
             port: ${{ secrets.PORT }}
             username: ${{ secrets.SSH_USER }}
             key: ${{ secrets.SSH_PRIVATE_KEY }} 
             
        
        
       
