name: Deploy
run-name: ${{ github.actor }} is deploying

on:
  workflow_run:
    workflows: ["Complete Tests"]
    types:
      - completed
      
jobs:  
  deploy:
     runs-on: ubuntu-latest  
     steps:
         - name: Set up SSH
           uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
           with:
              ssh-private-key: ${{ secrets.SSHKEY }}
              
         - name: Deploy app to droplet
           uses: appleboy/ssh-action@v0.1.4
           with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.USERNAME }}
             key: ${{ secrets.SSHKEY }}
             port: ${{ secrets.PORT }}
             script: ls
       
